#include <iostream>
using namespace std;
int main()
{
    int a;
    while(cin>>a)
    {
        if(a<0)
            a++;
        if(a%12==0)
        {
            cout<<"豬\n";
        }
        if(a%12==1||a%12==-11)
        {
            cout<<"鼠\n";
        }
        if(a%12==2||a%12==-10)
        {
            cout<<"牛\n";
        }
        if(a%12==3||a%12==-9)
        {
            cout<<"虎\n";
        }
        if(a%12==4||a%12==-8)
        {
            cout<<"兔\n";
        }
        if(a%12==5||a%12==-7)
        {
            cout<<"龍\n";
        }
        if(a%12==6||a%12==-6)
        {
            cout<<"蛇\n";
        }
        if(a%12==7||a%12==-5)
        {
            cout<<"馬\n";
        }
        if(a%12==8||a%12==-4)
        {
            cout<<"羊\n";
        }
        if(a%12==9||a%12==-3)
        {
            cout<<"猴\n";
        }
        if(a%12==10||a%12==-2)
        {
            cout<<"雞\n";
        }
        if(a%12==11||a%12==-1)
        {
            cout<<"狗\n";
        }
    }
}