#include <iostream>
using namespace std;
int main()
{
    int a;
    while(cin>>a)
    {
        a-=1800;
        if(a%10==0)
        {
            cout<<"庚";
        }
        if(a%10==1)
        {
            cout<<"辛";
        }
        if(a%10==2)
        {
            cout<<"壬";
        }
        if(a%10==3)
        {
            cout<<"癸";
        }
        if(a%10==4)
        {
            cout<<"甲";
        }
        if(a%10==5)
        {
            cout<<"乙";
        }
        if(a%10==6)
        {
            cout<<"丙";
        }
        if(a%10==7)
        {
            cout<<"丁";
        }
        if(a%10==8)
        {
            cout<<"戊";
        }
        if(a%10==9)
        {
            cout<<"己";
        }
        if(a%12==0)
        {
            cout<<"申";
        }
        if(a%12==1)
        {
            cout<<"酉";
        }
        if(a%12==2)
        {
            cout<<"戌";
        }
        if(a%12==3)
        {
            cout<<"亥";
        }
        if(a%12==4)
        {
            cout<<"子";
        }
        if(a%12==5)
        {
            cout<<"丑";
        }
        if(a%12==6)
        {
            cout<<"寅";
        }
        if(a%12==7)
        {
            cout<<"卯";
        }
        if(a%12==8)
        {
            cout<<"辰";
        }
        if(a%12==9)
        {
            cout<<"巳";
        }
        if(a%12==10)
        {
            cout<<"午";
        }
        if(a%12==11)
        {
            cout<<"未";
        }
        cout<<endl;
    }
}
